import type { ReceiveEmptyStateProps } from "../types";

export function ReceiveEmptyState({
  walletName,
  loading = false,
  error = null,
  onGenerate,
}: ReceiveEmptyStateProps) {
  const hasWallet = walletName.trim().length > 0;
  const canGenerate = hasWallet && !loading;
  const title = canGenerate
    ? "Generate a receive address"
    : "Select a wallet to receive Bitcoin";
  const buttonTitle = canGenerate
    ? "Generate the next wallet-controlled receive address"
    : "A wallet must be selected before generating an address";

  return (
    <section className="receive-empty">
      <div className="receive-empty__icon" aria-hidden="true">
        ↓
      </div>

      <div className="receive-empty__content">
        <p className="receive-empty__eyebrow">Receive</p>
        <h2 className="receive-empty__title">{title}</h2>
        <p className="receive-empty__description">
          Create the next wallet-controlled address and share it with the
          sender. The address is generated by the active wallet backend.
        </p>
      </div>

      {error ? (
        <div className="receive-empty__error" role="alert">
          {error}
        </div>
      ) : null}

      <button
        className="receive-empty__button"
        type="button"
        disabled={!canGenerate}
        title={buttonTitle}
        onClick={onGenerate}
      >
        {loading ? "Generating…" : "Generate receive address"}
      </button>
    </section>
  );
}
