network = "regtest"
db_dir = "/Users/alexandereygenson/MyRust/rust-descriptor-wallet/infra/regtest/electrs/db"
daemon_dir = "/Users/alexandereygenson/MyRust/rust-descriptor-wallet/infra/regtest/bitcoin/data"
daemon_rpc_addr = "127.0.0.1:18443"
daemon_p2p_addr = "127.0.0.1:18444"
electrum_rpc_addr = "127.0.0.1:60401"
monitoring_addr = "127.0.0.1:24224"
auth = "bitcoin:bitcoin"
skip_block_download_wait = true
